export const PublicRoutes = {
  signup: "/signup",
  signin: "/admin/signin",
  admin: "/admin",
  dashboard: "/admin/dashboard",
  password: "/admin/reset-password",
  permissions: "/admin/permissions",
  roles: "/admin/roles/list",
  addRole: "/admin/roles/add",
  editRole: "/admin/roles/edit",
  users: "/admin/users",
  addUser: "/admin/users/add-user",
  editUser: "/admin/users/edit-user",

  brand: "/admin/brand/list",
  addBrand: "/admin/brand/add",
  editBrand: "/admin/brand/update",
  categories: "/admin/categories",
  addCategory: "/admin/categories/add-category",
  editCategory: "/admin/categories/edit-category",
  shops: "/admin/shops",
  addShop: "/admin/shops/add-shop",
  editShop: "/admin/shops/edit-shop",
  profile: "/admin/profile",
  listings: "/admin/profile/listings",
  addListing: "/admin/profile/listings/add-listing",
  privacyPolicy: "/admin/privacy-policy",
  termsAndConditions: "/admin/terms",
  cart: "/admin/cart",
  checkout: "/admin/checkout",
};

export const AdminRoutes = {
  signup: '/signup',
  signin: '/admin/signin',
  admin: '/admin',
  dashboard: '/admin/dashboard',
  password: '/admin/reset-password',
  permissions: '/admin/permissions',
  roles: '/admin/roles/list',
  addRole: '/admin/roles/add',
  editRole: '/admin/roles/edit',
  users: '/admin/users',
  addUser: '/admin/users/add-user',
  editUser: '/admin/users/edit-user',

  brand: '/admin/brand/list',
  addBrand: '/admin/brand/add',
  editBrand: '/admin/brand/update',
  categories: '/admin/categories',
  addCategory: '/admin/categories/add-category',
  editCategory: '/admin/categories/edit-category',
  shops: '/admin/shops',
  addShop: '/admin/shops/add-shop',
  editShop: '/admin/shops/edit-shop',
  profile: '/admin/profile',
  listings: '/admin/profile/listings',
  addListing: '/admin/profile/listings/add-listing',
  privacyPolicy: '/admin/privacy-policy',
  termsAndConditions: '/admin/terms',
  cart: '/admin/cart',
  checkout: '/admin/checkout',
};
