-- GENERATED by scripts/generate-bionluk-seeds.mjs - do not edit by hand

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `testimonials` (
  `id` VARCHAR(64) NOT NULL,
  `source` ENUM('bionluk','direct') NOT NULL DEFAULT 'direct',
  `source_ref` VARCHAR(64) NULL,
  `initials` VARCHAR(16) NOT NULL,
  `rating` DECIMAL(2,1) NOT NULL,
  `review_date` DATE NOT NULL,
  `has_consent` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_featured` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `is_published` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `testimonials_source_ref_uq` (`source`,`source_ref`),
  KEY `testimonials_published_idx` (`is_published`),
  KEY `testimonials_featured_idx` (`is_featured`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `testimonials_i18n` (
  `id` VARCHAR(64) NOT NULL,
  `testimonial_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(5) NOT NULL,
  `role_title` VARCHAR(255) NULL,
  `quote` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `testimonials_i18n_uq` (`testimonial_id`,`locale`),
  CONSTRAINT `testimonials_i18n_fk` FOREIGN KEY (`testimonial_id`)
    REFERENCES `testimonials`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `testimonials` (`id`, `source`, `source_ref`, `initials`, `rating`, `review_date`, `has_consent`, `is_featured`, `is_published`, `sort_order`, `created_at`, `updated_at`) VALUES
('testimonial-1331819', 'bionluk', '1331819', 'F.S.', '5.0', '2026-06-10', 0, 1, 1, 1, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1329351', 'bionluk', '1329351', 'F.B.', '4.7', '2026-05-23', 0, 1, 1, 2, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1322757', 'bionluk', '1322757', 'B.B.', '5.0', '2026-04-12', 0, 1, 1, 3, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1319060', 'bionluk', '1319060', 'A.S.', '5.0', '2026-03-21', 0, 1, 1, 4, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1318498', 'bionluk', '1318498', 'A.S.', '5.0', '2026-03-17', 0, 1, 1, 5, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1293032', 'bionluk', '1293032', 'İ.S.', '5.0', '2025-10-27', 0, 0, 1, 6, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1286936', 'bionluk', '1286936', 'W.M.', '5.0', '2025-09-21', 0, 1, 1, 7, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1290767', 'bionluk', '1290767', 'F.M.', '5.0', '2025-10-14', 0, 0, 1, 8, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1286938', 'bionluk', '1286938', 'S.V.', '5.0', '2025-09-21', 0, 0, 1, 9, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000'),
('testimonial-1284917', 'bionluk', '1284917', 'S.V.', '5.0', '2025-09-10', 0, 0, 1, 10, '2026-06-11 20:51:13.000', '2026-06-11 20:51:13.000')
ON DUPLICATE KEY UPDATE `initials`=VALUES(`initials`), `rating`=VALUES(`rating`), `review_date`=VALUES(`review_date`), `has_consent`=VALUES(`has_consent`), `is_featured`=VALUES(`is_featured`), `is_published`=VALUES(`is_published`), `sort_order`=VALUES(`sort_order`), `updated_at`=VALUES(`updated_at`);

INSERT INTO `testimonials_i18n` (`id`, `testimonial_id`, `locale`, `role_title`, `quote`) VALUES
('testimonial-i18n-tr-1331819', 'testimonial-1331819', 'tr', 'Yazılım ve İhracat', 'Orhan hocam ile yeni nesil, yani Google''un seveceği, yukarılarda göstereceği hızlı açılan website konusunda çalışma yaptık. Bu çalışmayı Cloudflare domain adı, Next.js yazılım dili ve Hostinger VPS sağlayıcı kullanarak sağladık. Kendisi bu kavramlara uzak değildi, süreci güzel yönetti. Teşekkürler.'),
('testimonial-i18n-en-1331819', 'testimonial-1331819', 'en', 'Software & Export', 'We worked on a next-generation website — the kind Google favours and ranks well — that loads fast. We built it using a Cloudflare domain, the Next.js framework and a Hostinger VPS. He was well versed in these concepts and managed the process nicely. Thank you.'),
('testimonial-i18n-tr-1329351', 'testimonial-1329351', 'tr', 'Amazon FBA operasyon ve karar sistemleri', 'İletişim ve teknik geri dönüş tarafı oldukça iyiydi. Canlı testlerde çıkan sorunlara hızlı dönüş sağlayıp gerekli düzeltmeleri yaptı. Çalışan ve operasyonel olarak kullanılabilir bir V1 sistem teslim edildi. Süreç boyunca çözüm odaklı ve iteratif ilerledi. Teşekkür ederim.'),
('testimonial-i18n-en-1329351', 'testimonial-1329351', 'en', 'Amazon FBA operations & decision systems', 'Communication and technical responsiveness were very good. He responded quickly to issues found in live testing and made the necessary corrections. A working, operationally usable V1 system was delivered. Throughout the process he worked iteratively and stayed solution-focused. Thank you.'),
('testimonial-i18n-tr-1322757', 'testimonial-1322757', 'tr', 'Sosyal Medya Danışmanı', 'Gerçekten son zamanlarda çalıştığım en iyi freelancer; SEO ve kodlama konusunda kendini aşmış biri. SEO optimizasyonu tamamlandı, şimdi geriye kalan işlemleri teslim etmek için çalışmaya devam ediyor.'),
('testimonial-i18n-en-1322757', 'testimonial-1322757', 'en', 'Social Media Consultant', 'Genuinely the best freelancer I have worked with recently — he has outdone himself on SEO and coding. The SEO optimisation is complete and he is still working to deliver the remaining items.'),
('testimonial-i18n-tr-1319060', 'testimonial-1319060', 'tr', NULL, 'Gerçekten işinin ehli. Her probleme hızlıca çözüm üretebiliyor. Desteğini esirgemiyor. Bundan sonra sürekli olarak çalışacağız.'),
('testimonial-i18n-en-1319060', 'testimonial-1319060', 'en', NULL, 'Truly a master of his craft. He produces quick solutions to every problem and never withholds his support. We will be working together on an ongoing basis from now on.'),
('testimonial-i18n-tr-1318498', 'testimonial-1318498', 'tr', NULL, 'İşinde profesyonel, isteklerinizi rahatça dile getirebilirsiniz. Web sitem için çok teknik bir altyapı, anlaşılır ve süper işlevsel bir admin paneli kurdu. Basit bir website değil, resmen sistem yaratıyor. Kesinlikle çalışmaya devam edeceğim.'),
('testimonial-i18n-en-1318498', 'testimonial-1318498', 'en', NULL, 'Professional in his work; you can express your requests comfortably. He built a highly technical infrastructure for my website along with a clear, superbly functional admin panel. This is not a simple website — he genuinely creates a system. I will definitely keep working with him.'),
('testimonial-i18n-tr-1293032', 'testimonial-1293032', 'tr', NULL, 'İşini severek ve çok hızlı yapıyor. Kısa sürede işi tamamladı. Kendisiyle çalışmaktan çok memnun oldum.'),
('testimonial-i18n-en-1293032', 'testimonial-1293032', 'en', NULL, 'He does his work with genuine enthusiasm and great speed. He completed the job in a short time. I was very pleased to work with him.'),
('testimonial-i18n-tr-1286936', 'testimonial-1286936', 'tr', 'Yazılım Uzmanı', 'Orhan ile çalışmak büyük bir keyifti. İşi zamanında ve eksiksiz teslim etti; teknik detaylara hâkimiyeti ve iletişim becerisi gerçekten etkileyiciydi. Taleplerimi sabırla dinledi, her aşamasında çözüm odaklı yaklaştı. Hem profesyonel hem de güvenilir bir freelancer, tavsiye ediyorum herkese.'),
('testimonial-i18n-en-1286936', 'testimonial-1286936', 'en', 'Software Specialist', 'Working with Orhan was a great pleasure. He delivered the work on time and in full; his command of technical detail and his communication skills were genuinely impressive. He listened to my requests patiently and stayed solution-focused at every stage. A professional and trustworthy freelancer — I recommend him to everyone.'),
('testimonial-i18n-tr-1290767', 'testimonial-1290767', 'tr', NULL, 'Çok hızlı hizmet.'),
('testimonial-i18n-en-1290767', 'testimonial-1290767', 'en', NULL, 'Very fast service.'),
('testimonial-i18n-tr-1286938', 'testimonial-1286938', 'tr', NULL, 'Teşekkürler, her şey için.'),
('testimonial-i18n-en-1286938', 'testimonial-1286938', 'en', NULL, 'Thank you, for everything.'),
('testimonial-i18n-tr-1284917', 'testimonial-1284917', 'tr', NULL, 'Güzel iş.'),
('testimonial-i18n-en-1284917', 'testimonial-1284917', 'en', NULL, 'Nice work.')
ON DUPLICATE KEY UPDATE `role_title`=VALUES(`role_title`), `quote`=VALUES(`quote`);
