// =============================================================
// FILE: src/config/admin-ui-defaults.ts
//
// PANEL METINLERI — TEK KAYNAK
//
// NEDEN VAR (2026-08-09):
//   Panel metinleri `site_settings.ui_admin` anahtarindan geliyor ve
//   `normalizeAdminUiCopy` eksik anahtarlari BOS DIZGE olarak donduruyordu.
//   gzlteknoloji.com panelinde bu ayarin yalnizca `pages.dashboard` bolumu
//   doluydu; sonuc olarak projeler, markalar, fiyatlar, ozgecmis, yetenekler,
//   bulten, mesajlar ve posta sayfalarinda BASLIKLAR VE SUTUN ADLARI BOS
//   goruntuleniyordu — sayfa okunamaz haldeydi.
//
// COZUM — tek kanal, dinamik:
//   1) Varsayilanlar burada, markadan bagimsiz ve Turkce olarak tanimli.
//   2) `ui_admin` ayari bu varsayilanlarin UZERINE yazilir (derin birlestirme).
//      Yani panelden yapilan her degisiklik yine tek kanaldan (DB) gelir.
//   3) DB'de olmayan anahtar artik bos degil, buradaki makul karsiligidir.
//
//   Marka adi BURADA YOK: o `company_brand` / `site_title` ayarindan okunur
//   (bkz. src/config/app-config.ts). Kod tabanina marka gomulmez.
// =============================================================

/** Birden fazla sayfada aynen tekrar eden alan adlari. */
const V = {
  col_actions: 'İşlemler',
  col_active: 'Durum',
  col_code: 'Kod',
  col_created: 'Oluşturma',
  col_currency: 'Para birimi',
  col_dates: 'Tarihler',
  col_email: 'E-posta',
  col_featured: 'Öne çıkan',
  col_label: 'Etiket',
  col_locale: 'Dil',
  col_name: 'Ad',
  col_order: 'Sıra',
  col_percent: 'Yüzde',
  col_price: 'Fiyat',
  col_published: 'Yayın',
  col_sale: 'İndirimli',
  col_status: 'Durum',
  col_subject: 'Konu',
  col_subscribed: 'Abone',
  col_title: 'Başlık',
  col_track: 'Kolon',
  col_type: 'Tür',
  col_verified: 'Doğrulanmış',
  filter_all: 'Tümü',
  filter_yes: 'Evet',
  filter_no: 'Hayır',
  filters_title: 'Filtreler',
  filters_desc: 'Listeyi daraltmak için filtreleri kullanın.',
  list_title: 'Kayıtlar',
  list_desc: 'Mevcut kayıtlar aşağıda listelenir.',
  locale_label: 'Dil',
  order_label: 'Sıralama',
  order_asc: 'Artan',
  order_desc: 'Azalan',
  search_ph: 'Ara…',
  active_label: 'Aktif',
  active_yes: 'Aktif',
  active_no: 'Pasif',
  active_only: 'Yalnızca aktifler',
  featured_label: 'Öne çıkan',
  featured_yes: 'Evet',
  featured_no: 'Hayır',
  published_label: 'Yayın durumu',
  delete_confirm: 'Bu kaydı silmek istediğinize emin misiniz?',
  required_error: 'Bu alan zorunludur.',
  track_label: 'Kolon',
  track_all: 'Tümü',
  track_left: 'Sol',
  track_right: 'Sağ',
  type_label: 'Tür',
  type_education: 'Eğitim',
  type_experience: 'Deneyim',
  slug_label: 'Adres (slug)',
  title_label: 'Başlık',
  description_label: 'Açıklama',
  meta_title: 'Meta başlık',
  meta_desc: 'Meta açıklama',
  meta_title_label: 'Meta başlık',
  meta_description_label: 'Meta açıklama',
  form_title: 'Bilgiler',
  form_desc: 'Alanları doldurup kaydedin.',
  start_date_label: 'Başlangıç tarihi',
  end_date_label: 'Bitiş tarihi',
  currency_label: 'Para birimi',
} as const;

type Copy = Record<string, string>;

const projects: Copy = {
  title: 'Projeler',
  subtitle: 'Portföyde yayımlanan proje kayıtları.',
  col_title: V.col_title,
  col_locale: V.col_locale,
  col_published: V.col_published,
  col_featured: V.col_featured,
  col_price: V.col_price,
  col_sale: V.col_sale,
  col_order: V.col_order,
  col_actions: V.col_actions,
  filters_title: V.filters_title,
  filters_desc: 'Dil, yayın durumu ve öne çıkarma durumuna göre süzün.',
  filter_all: V.filter_all,
  filter_yes: V.filter_yes,
  filter_no: V.filter_no,
  list_title: 'Proje listesi',
  list_desc: 'Sıralama, yayın durumu ve SEO puanı bu tablodan izlenir.',
  locale_label: V.locale_label,
  published_label: V.published_label,
  featured_label: V.featured_label,
  search_ph: 'Proje adı veya slug ara…',
};

const projects_detail: Copy = {
  create_title: 'Yeni proje',
  edit_title: 'Projeyi düzenle',
  subtitle: 'Proje içeriği, görselleri ve SEO alanları.',
  form_title: V.form_title,
  form_desc: 'Zorunlu alanlar doldurulmadan kayıt tamamlanmaz.',
  title_label: V.title_label,
  slug_label: V.slug_label,
  locale_label: V.locale_label,
  summary_label: 'Özet',
  content_label: 'İçerik',
  category_label: 'Kategori',
  client_label: 'Müşteri',
  website_url_label: 'Web sitesi adresi',
  demo_url_label: 'Demo adresi',
  repo_url_label: 'Kod deposu adresi',
  start_date_label: V.start_date_label,
  complete_date_label: 'Tamamlanma tarihi',
  completion_time_label: 'Tamamlanma süresi',
  price_onetime_label: 'Tek seferlik fiyat',
  currency_label: V.currency_label,
  is_purchasable_label: 'Satın alınabilir',
  published_label: V.published_label,
  featured_label: V.featured_label,
  order_label: V.order_label,
  featured_image_label: 'Kapak görseli',
  featured_image_alt_label: 'Kapak görseli alt metni',
  featured_image_asset_label: 'Kapak görseli varlığı',
  techs_label: 'Teknolojiler',
  techs_help: 'Virgülle ayırarak yazın.',
  services_label: 'İlgili hizmetler',
  services_help: 'Bu projede verilen hizmetleri seçin.',
  meta_title: V.meta_title,
  meta_desc: V.meta_desc,
  meta_title_label: V.meta_title_label,
  meta_description_label: V.meta_description_label,
  required_error: V.required_error,
};

const brands: Copy = {
  title: 'Markalar',
  subtitle: 'Sitede gösterilen marka ve referans logoları.',
  col_label: V.col_label,
  col_locale: V.col_locale,
  col_active: V.col_active,
  col_order: V.col_order,
  col_track: V.col_track,
  col_actions: V.col_actions,
  filters_title: V.filters_title,
  filters_desc: 'Dil ve durum filtreleriyle listeyi daraltın.',
  list_title: 'Marka listesi',
  list_desc: 'Logolar akış (track) bazında sıralanır.',
  create_title: 'Yeni marka',
  edit_title: 'Markayı düzenle',
  label_label: 'Marka adı',
  label_ph: 'Örn. Ensotek',
  label_required: 'Marka adı zorunludur.',
  image_url_label: 'Logo adresi',
  image_url_ph: '/uploads/…',
  asset_id_label: 'Görsel varlığı',
  asset_id_ph: 'Varlık kimliği',
  locale_label: V.locale_label,
  order_label: V.order_label,
  active_label: V.active_label,
  active_yes: V.active_yes,
  active_no: V.active_no,
  active_only: V.active_only,
  track_label: V.track_label,
  track_all: V.track_all,
  track_left: V.track_left,
  track_right: V.track_right,
  delete_confirm: V.delete_confirm,
};

const contacts: Copy = {
  title: 'Mesajlar',
  subtitle: 'İletişim formundan gelen talepler.',
  col_name: V.col_name,
  col_email: V.col_email,
  col_subject: V.col_subject,
  col_status: V.col_status,
  col_created: V.col_created,
  col_actions: V.col_actions,
  filters_title: V.filters_title,
  filters_desc: 'Durum ve sıralama seçenekleriyle süzün.',
  list_title: 'Gelen mesajlar',
  list_desc: 'Yanıtlanan mesajları çözümlendi olarak işaretleyin.',
  edit_title: 'Mesaj detayı',
  edit_desc: 'Mesajı okuyun, notunuzu ekleyin ve durumunu güncelleyin.',
  search_ph: 'Ad, e-posta veya konu ara…',
  status_label: 'Durum',
  status_all: V.filter_all,
  status_new: 'Yeni',
  status_in_progress: 'İşlemde',
  status_closed: 'Kapandı',
  resolved_label: 'Çözümlendi',
  only_unresolved: 'Yalnızca çözümlenmemişler',
  admin_note_label: 'Yönetici notu',
  admin_note_ph: 'İç not (müşteri görmez)',
  order_label: V.order_label,
  order_asc: V.order_asc,
  order_desc: V.order_desc,
  order_by_label: 'Sıralama alanı',
  order_by_created: 'Oluşturma tarihi',
  order_by_updated: 'Güncelleme tarihi',
  order_by_name: 'Ad',
  order_by_status: 'Durum',
  delete_confirm: V.delete_confirm,
};

const newsletter: Copy = {
  title: 'Bülten',
  subtitle: 'E-posta bültenine kayıtlı adresler.',
  col_email: V.col_email,
  col_subscribed: V.col_subscribed,
  col_verified: V.col_verified,
  col_created: V.col_created,
  col_actions: V.col_actions,
  filters_title: V.filters_title,
  filters_desc: 'Abonelik ve doğrulama durumuna göre süzün.',
  filter_all: V.filter_all,
  filter_yes: V.filter_yes,
  filter_no: V.filter_no,
  list_title: 'Aboneler',
  list_desc: 'Doğrulanmamış adreslere gönderim yapılmaz.',
  edit_title: 'Abone kaydı',
  search_ph: 'E-posta ara…',
  subscribed_label: 'Abonelik',
  verified_label: 'Doğrulama',
  meta_label: 'Ek bilgi',
  meta_help: 'Kaynak, kampanya gibi serbest alanlar.',
  order_label: V.order_label,
  order_asc: V.order_asc,
  order_desc: V.order_desc,
  delete_confirm: V.delete_confirm,
};

const pricing: Copy = {
  title: 'Fiyatlar',
  subtitle: 'Sitede gösterilen paket ve fiyat kartları.',
  col_code: V.col_code,
  col_price: V.col_price,
  col_currency: V.col_currency,
  col_active: V.col_active,
  col_featured: V.col_featured,
  col_order: V.col_order,
  col_actions: V.col_actions,
  active_yes: V.active_yes,
  active_no: V.active_no,
  featured_yes: V.featured_yes,
  featured_no: V.featured_no,
  list_title: 'Paket listesi',
  list_desc: 'Öne çıkan paket sitede vurgulu gösterilir.',
};

const pricing_detail: Copy = {
  create_title: 'Yeni paket',
  edit_title: 'Paketi düzenle',
  subtitle: 'Paket kodu, fiyatı ve görünürlüğü.',
  form_title: V.form_title,
  form_desc: 'Kod alanı benzersiz olmalıdır.',
  code_label: 'Paket kodu',
  code_required: 'Paket kodu zorunludur.',
  price_amount_label: 'Fiyat',
  price_unit_label: 'Birim',
  currency_label: V.currency_label,
  cta_href_label: 'Buton adresi',
  active_label: V.active_label,
  featured_label: V.featured_label,
  order_label: V.order_label,
  i: '',
};

const resume: Copy = {
  title: 'Özgeçmiş',
  subtitle: 'Deneyim ve eğitim kayıtları.',
  col_title: V.col_title,
  col_type: V.col_type,
  col_dates: V.col_dates,
  col_active: V.col_active,
  col_actions: V.col_actions,
  filters_title: V.filters_title,
  filters_desc: 'Dil, tür ve durum filtreleri.',
  filter_all: V.filter_all,
  filter_yes: V.filter_yes,
  filter_no: V.filter_no,
  list_title: 'Kayıt listesi',
  list_desc: 'Sitede kronolojik sırayla gösterilir.',
  locale_label: V.locale_label,
  active_label: V.active_label,
  type_label: V.type_label,
  type_education: V.type_education,
  type_experience: V.type_experience,
  present_label: 'Devam ediyor',
  search_ph: 'Kurum veya başlık ara…',
};

const resume_detail: Copy = {
  create_title: 'Yeni kayıt',
  edit_title: 'Kaydı düzenle',
  subtitle: 'Deneyim veya eğitim kaydının ayrıntıları.',
  form_title: V.form_title,
  form_desc: 'Tarih alanları boş bırakılırsa kayıt tarihsiz gösterilir.',
  title_label: V.title_label,
  subtitle_label: 'Alt başlık',
  organization_label: 'Kurum',
  location_label: 'Konum',
  description_label: V.description_label,
  highlights_label: 'Öne çıkanlar',
  highlights_help: 'Her satıra bir madde yazın.',
  type_label: V.type_label,
  type_education: V.type_education,
  type_experience: V.type_experience,
  start_date_label: V.start_date_label,
  end_date_label: V.end_date_label,
  current_label: 'Halen devam ediyor',
  score_scale_label: 'Not ölçeği',
  score_value_label: 'Not',
  slug_label: V.slug_label,
  locale_label: V.locale_label,
  active_label: V.active_label,
  order_label: V.order_label,
  meta_title: V.meta_title,
  meta_desc: V.meta_desc,
  required_error: V.required_error,
};

const skills: Copy = {
  title: 'Yetenekler',
  subtitle: 'Yetenek sayaçları ve teknoloji logoları.',
  col_title: V.col_title,
  col_label: V.col_label,
  col_percent: V.col_percent,
  col_locale: V.col_locale,
  col_active: V.col_active,
  col_track: V.col_track,
  col_actions: V.col_actions,
  filters_title: V.filters_title,
  filters_desc: 'Dil ve durum filtreleri.',
  locale_label: V.locale_label,
  active_yes: V.active_yes,
  active_no: V.active_no,
  active_only: V.active_only,
  counters_title: 'Sayaçlar',
  counters_desc: 'Yüzde ile gösterilen yetenek çubukları.',
  counter_create_title: 'Yeni sayaç',
  counter_edit_title: 'Sayacı düzenle',
  counter_required: 'Sayaç başlığı zorunludur.',
  logos_title: 'Logolar',
  logos_desc: 'Teknoloji ve araç logoları.',
  logo_create_title: 'Yeni logo',
  logo_edit_title: 'Logoyu düzenle',
  logo_required: 'Logo etiketi zorunludur.',
  track_label: V.track_label,
  track_all: V.track_all,
  track_left: V.track_left,
  track_right: V.track_right,
};

const mail: Copy = {
  title: 'Posta',
  subtitle: 'Giden e-posta ayarlarının denetimi.',
  info_title: 'Gönderim bilgileri',
  info_description: 'Aşağıdaki değerler sunucu ortam ayarlarından okunur.',
  info_line: 'Ayarlar `.env` dosyasından gelir; panelden değiştirilemez.',
  test_section_title: 'Test e-postası',
  test_section_description: 'Kurulumun çalıştığını doğrulamak için kendinize bir deneme gönderin.',
  email_label: 'Alıcı adresi',
  email_placeholder: 'ornek@alanadi.com',
  send_test: 'Test gönder',
  sending: 'Gönderiliyor…',
  test_mail_sent: 'Test e-postası gönderildi.',
};

const dashboard: Copy = {
  title: 'Panel',
  subtitle: 'Özet göstergeler ve son hareketler.',
};

/**
 * Varsayilan panel metinleri. `site_settings.ui_admin` bu nesnenin UZERINE
 * yazilir; buradaki degerler yalnizca DB'de karsiligi olmayan anahtarlar icin
 * devreye girer.
 */
export const ADMIN_UI_DEFAULTS = {
  // Marka adi DB'den gelir (site_settings.ui_admin -> app_name). Buradaki
  // deger yalnizca o alan bosken gorunur; marka adi YAZILMAZ.
  app_name: 'Yönetim Paneli',
  nav: {
    items: {
      dashboard: 'Panel',
      site_settings: 'Site Ayarları',
      custom_pages: 'Sayfalar',
      services: 'Hizmetler',
      projects: 'Projeler',
      products: 'Ürünler',
      pricing: 'Fiyatlar',
      brands: 'Markalar',
      resume: 'Özgeçmiş',
      skills: 'Yetenekler',
      menu_items: 'Menü Öğeleri',
      footer_sections: 'Footer Bölümleri',
      faqs: 'Sık Sorulanlar',
      social_posts: 'Sosyal Gönderiler',
      newsletter: 'Bülten',
      contacts: 'Mesajlar',
      reviews: 'Yorumlar',
      support: 'Destek',
      chat: 'Sohbet',
      mail: 'Posta',
      users: 'Kullanıcılar',
      email_templates: 'E-posta Şablonları',
      notifications: 'Bildirimler',
      storage: 'Dosyalar',
      db: 'Veritabanı',
      audit: 'Denetim',
      orders: 'Siparişler',
      user_roles: 'Roller',
    },
    labels: {
      general: 'Genel',
      content: 'İçerik',
      marketing: 'Pazarlama',
      communication: 'İletişim',
      system: 'Sistem',
    },
  },
  common: {
    actions: {
      create: 'Yeni',
      edit: 'Düzenle',
      delete: 'Sil',
      save: 'Kaydet',
      cancel: 'Vazgeç',
      refresh: 'Yenile',
      search: 'Ara',
      filter: 'Filtrele',
      close: 'Kapat',
      back: 'Geri',
      confirm: 'Onayla',
    },
    states: {
      loading: 'Yükleniyor…',
      error: 'Kayıtlar getirilemedi.',
      empty: 'Kayıt bulunamadı.',
      updating: 'Güncelleniyor…',
    },
  },
  pages: {
    dashboard,
    projects,
    projects_detail,
    brands,
    contacts,
    newsletter,
    pricing,
    pricing_detail,
    resume,
    resume_detail,
    skills,
    mail,
  },
} as const;
