SET NAMES utf8mb4;

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`)
VALUES ('a84e3de2-c47b-5a50-9d4d-cd8950e54601', 'content_categories', 'de', '{"items":[{"slug":"web-ecommerce","label":"Web & E-Commerce","description":"Unternehmensseiten, E-Commerce, Buchungs- und Bestellsysteme.","order":1},{"slug":"custom-software","label":"Individualsoftware & ERP","description":"Prozessspezifische Webanwendungen, ERP und Verwaltungspanels.","order":2},{"slug":"data-automation","label":"Daten, Automatisierung & KI","description":"Datenerfassung, Prognosemodelle und Automatisierungspanels.","order":3},{"slug":"seo-geo","label":"SEO, GEO & Analytics","description":"Sichtbarkeit in Suche und KI, Analytics und Conversion-Tracking.","order":4},{"slug":"infra-support","label":"Infrastruktur & Wartung","description":"Servereinrichtung, Deployment, Monitoring und laufende Wartung.","order":5}]}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`)
VALUES ('a84e3de2-c47b-5a50-9d4d-cd8950e54602', 'content_categories', 'en', '{"items":[{"slug":"web-ecommerce","label":"Web & E-Commerce","description":"Corporate sites, e-commerce, booking and ordering systems.","order":1},{"slug":"custom-software","label":"Custom Software & ERP","description":"Process-specific web applications, ERP and management panels.","order":2},{"slug":"data-automation","label":"Data, Automation & AI","description":"Data collection, prediction models and automation panels.","order":3},{"slug":"seo-geo","label":"SEO, GEO & Analytics","description":"Search and AI visibility, analytics and conversion tracking.","order":4},{"slug":"infra-support","label":"Infrastructure & Support","description":"Server setup, deployment, monitoring and ongoing maintenance.","order":5}]}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`)
VALUES ('a84e3de2-c47b-5a50-9d4d-cd8950e54603', 'content_categories', 'tr', '{"items":[{"slug":"web-ecommerce","label":"Web ve E-Ticaret","description":"Kurumsal siteler, e-ticaret, randevu ve sipariş sistemleri.","order":1},{"slug":"custom-software","label":"Özel Yazılım ve ERP","description":"İş süreçlerine özgü web uygulamaları, ERP ve yönetim panelleri.","order":2},{"slug":"data-automation","label":"Veri, Otomasyon ve Yapay Zekâ","description":"Veri toplama, tahmin modelleri ve otomasyon panelleri.","order":3},{"slug":"seo-geo","label":"SEO, GEO ve Ölçümleme","description":"Arama motoru ve yapay zekâ görünürlüğü, analitik kurulumu.","order":4},{"slug":"infra-support","label":"Altyapı ve Bakım","description":"Sunucu kurulumu, yayına alma, izleme ve sürekli bakım.","order":5}]}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);
