-- =============================================================
-- @generated migrate-gzlteknoloji-content
-- OTOMATIK URETILDI — ELLE DUZENLEMEYIN.
-- Uretici : backend/scripts/migrate-gzlteknoloji-content.mjs
-- Kaynak  : _migration/gzlteknoloji/content-seeds/sql/047_legal_policy_content_seed.sql
-- Gerekce : KVKK/gizlilik/cerez/mesafeli satis vb. (plan madde 8)
--
-- Yeniden uretmek icin: bun run migrate:gzl
-- =============================================================

SET NAMES utf8mb4;
-- GENERATED by scripts/generate-legal-policy-seed.mjs

SET NAMES utf8mb4;

INSERT INTO custom_pages (id,module_key,is_published,display_order,created_at,updated_at) VALUES
('47000000-0000-4000-8000-000000000001','privacy',1,1,'2026-07-11 00:00:00.000','2026-07-11 00:00:00.000'),
('47000000-0000-4000-8000-000000000002','terms',1,2,'2026-07-11 00:00:00.000','2026-07-11 00:00:00.000'),
('47000000-0000-4000-8000-000000000003','cookies',1,3,'2026-07-11 00:00:00.000','2026-07-11 00:00:00.000')
ON DUPLICATE KEY UPDATE module_key=VALUES(module_key),is_published=VALUES(is_published),display_order=VALUES(display_order),updated_at=VALUES(updated_at);

INSERT INTO custom_pages_i18n (`id`,`page_id`,`locale`,`title`,`slug`,`content`,`summary`,`meta_title`,`meta_description`) VALUES
  ('7ebe9b5a-89d4-4960-bc71-ea4e8e6801cd','47000000-0000-4000-8000-000000000001','tr','Gizlilik Politikası','privacy-policy','<p><strong>Yürürlük tarihi: 11 Temmuz 2026</strong></p>
<p>Bu politika, gzlteknoloji.com internet sitesinde kişisel verilerin hangi kapsamda işlendiğini açıklar. Veri sorumlusu, <strong>GZL Danışmanlık Hizmetleri ve Teknoloji Ltd. Şti.</strong>’dir. Merkezimiz Gemlik/Bursa’dadır. Gizlilik talepleri için info@gzlteknoloji.com adresinden bize ulaşabilirsiniz.</p>
<h2>1. İşlediğimiz veriler</h2>
<ul><li>Teklif ve iletişim formlarında ad-soyad, e-posta, telefon, firma, bütçe/zamanlama, mesaj ve seçilen hizmet veya paket bilgileri,</li><li>Form güvenliği kapsamında IP adresi, tarayıcı bilgisi ve istenmeyen otomatik gönderimleri ayırt etmeye yarayan teknik kayıtlar,</li><li>E-bülten kaydında e-posta adresi, dil tercihi ve onay kaydı,</li><li>Site güvenliği kapsamında erişim ve hata kayıtları,</li><li>Açık rıza verilmesi hâlinde analitik kullanım ve cihaz verileri işlenebilir.</li></ul>
<h2>2. İşleme amaçları ve hukuki sebepler</h2>
<p>Veriler; talepleri yanıtlamak, teklif hazırlamak, sözleşme öncesi süreçleri yürütmek, hizmet sunmak, destek sağlamak, güvenliği korumak, kötüye kullanımı önlemek ve yasal yükümlülükleri yerine getirmek amacıyla işlenir. İşleme faaliyeti, durumuna göre sözleşmenin kurulması veya ifası, hukuki yükümlülük, bir hakkın tesisi veya korunması, temel haklara zarar vermeyen meşru menfaat ya da açık rıza şartına dayanır.</p>
<p>Pazarlama amaçlı elektronik ileti, hizmet talebine verilen yanıttan ayrıdır. Bu iletiler yalnızca gerekli onay alındığında gönderilir; onay ve ret kayıtları ilgili mevzuat kapsamında İleti Yönetim Sistemi üzerinden yönetilebilir.</p>
<h2>3. Verilerin paylaşılması</h2>
<p>Kişisel veriler satılmaz. Veriler yalnızca hizmetin gerektirdiği ölçüde barındırma, e-posta, güvenlik, ödeme, muhasebe ve yetkili teknik hizmet sağlayıcılarla; ayrıca hukuki zorunluluk hâlinde yetkili kamu kurumlarıyla paylaşılabilir. Hizmet sağlayıcılar verileri yalnızca ilgili hizmetin sunulması amacıyla işler.</p>
<h2>4. Analitik ve yurt dışına aktarım</h2>
<p>Analitik araçlar varsayılan olarak kapalıdır. Ziyaretçi çerez tercih ekranında analitik kullanımına onay verirse Google Analytics 4 ve Google Tag Manager etkinleşebilir. Bu durumda cihaz ve kullanım verileri Google’ın yurt dışındaki sistemlerinde işlenebilir. Ayrıntılar ve kullanılan çerezler Çerez Politikası’nda açıklanır. Onay verilmemesi, sitenin temel işlevlerini engellemez.</p>
<h2>5. Saklama ve güvenlik</h2>
<p>Veriler, işleme amacı ve ilgili mevzuatın gerektirdiği süreyle sınırlı tutulur. Teklif ve sözleşme kayıtları hukuki ve ticari yükümlülükler süresince; bülten kayıtları üyelik veya onay sona erene kadar; güvenlik kayıtları ise güvenlik ihtiyacının gerektirdiği makul süre boyunca saklanır. Yetkisiz erişimi, değişikliği ve kaybı önlemek için uygun teknik ve idari önlemler uygulanır.</p>
<h2>6. Haklarınız</h2>
<p>6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında; verilerinizin işlenip işlenmediğini öğrenme, bilgi talep etme, işleme amacını ve aktarılan tarafları öğrenme, yanlış verilerin düzeltilmesini, şartları oluştuğunda silinmesini veya yok edilmesini isteme, otomatik analiz sonucuna itiraz etme ve hukuka aykırı işleme nedeniyle zararın giderilmesini talep etme haklarına sahipsiniz.</p>
<p>Başvurunuzu kimliğinizi doğrulamaya elverişli bilgilerle info@gzlteknoloji.com adresine veya şirket adresimize iletebilirsiniz. Başvurular, niteliğine göre en kısa sürede ve en geç 30 gün içinde sonuçlandırılır.</p>
<h2>7. Politika değişiklikleri</h2>
<p>Mevzuat, hizmetler veya kullanılan teknik altyapı değiştiğinde bu politika güncellenebilir. Güncel sürüm ve yürürlük tarihi bu sayfada yayımlanır.</p>','GZL Teknoloji kişisel verilerin işlenmesi, korunması, paylaşılması ve KVKK kapsamındaki haklar hakkında gizlilik politikası.','Gizlilik Politikası','GZL Teknoloji kişisel verilerin işlenmesi, korunması, paylaşılması ve KVKK kapsamındaki haklar hakkında gizlilik politikası.'),
  ('4dc9560a-b6d8-4217-b678-c9128037799a','47000000-0000-4000-8000-000000000001','en','Privacy Policy','privacy-policy','<p><strong>Effective date: 11 July 2026</strong></p>
<p>This policy explains how personal data is processed on gzlteknoloji.com. The data controller is <strong>GZL Danışmanlık Hizmetleri ve Teknoloji Ltd. Şti.</strong>, based in Gemlik, Bursa, Türkiye. Privacy requests may be sent to info@gzlteknoloji.com.</p>
<h2>1. Data we process</h2>
<ul><li>Name, email, telephone, company, budget/timing, message and selected service or package information submitted through quote and contact forms,</li><li>IP address, browser information and technical records used to protect forms against abuse and automated submissions,</li><li>Email address, language preference and consent record for newsletter subscriptions,</li><li>Access and error records needed for website security,</li><li>Analytics usage and device data where consent has been given.</li></ul>
<h2>2. Purposes and legal grounds</h2>
<p>Data is processed to answer requests, prepare proposals, manage pre-contractual steps, provide services and support, protect security, prevent abuse and comply with legal duties. Depending on the activity, processing relies on contract performance, a legal obligation, establishment or protection of a right, legitimate interests that do not override fundamental rights, or consent.</p>
<p>Marketing messages are separate from replies to service requests. They are sent only where the required permission exists, and consent or opt-out records may be managed through Türkiye’s Message Management System under applicable law.</p>
<h2>3. Sharing</h2>
<p>Personal data is not sold. It may be shared only where necessary with hosting, email, security, payment, accounting and authorised technical service providers, or with public authorities where legally required. Providers may process data only for the relevant service.</p>
<h2>4. Analytics and international transfers</h2>
<p>Analytics tools are disabled by default. If analytics consent is given through the cookie preference interface, Google Analytics 4 and Google Tag Manager may be activated. Device and usage data may then be processed in Google systems outside Türkiye. The Cookie Policy describes the relevant cookies. Refusing analytics does not prevent use of essential website functions.</p>
<h2>5. Retention and security</h2>
<p>Data is retained only for the period required by its purpose and applicable law. Proposal and contract records are retained for legal and commercial obligations, newsletter data until subscription or consent ends, and security records for a reasonable period required for security. Appropriate technical and organisational safeguards are applied.</p>
<h2>6. Your rights</h2>
<p>Under Turkish Law No. 6698, you may ask whether your data is processed, request information, learn the purpose and recipients, request correction, request deletion or destruction where the legal conditions exist, object to certain automated results and seek compensation for unlawful processing.</p>
<p>Requests may be sent with sufficient identity information to info@gzlteknoloji.com or to the company address. Requests are answered as soon as possible and no later than 30 days, subject to applicable law.</p>
<h2>7. Changes</h2>
<p>This policy may be updated when law, services or technical infrastructure changes. The current version and effective date are published on this page.</p>','GZL Technology privacy policy covering personal-data processing, security, sharing and data-subject rights.','Privacy Policy','GZL Technology privacy policy covering personal-data processing, security, sharing and data-subject rights.'),
  ('2d7b153f-d6f8-443e-9b48-c852114546a8','47000000-0000-4000-8000-000000000002','tr','Kullanım Koşulları','terms','<p><strong>Yürürlük tarihi: 11 Temmuz 2026</strong></p>
<p>Bu koşullar gzlteknoloji.com internet sitesinin kullanımını düzenler. Site, <strong>GZL Danışmanlık Hizmetleri ve Teknoloji Ltd. Şti.</strong> tarafından işletilmektedir.</p>
<h2>1. Kapsam</h2>
<p>Site; yazılım geliştirme, web sitesi, e-ticaret, otomasyon, danışmanlık, bakım ve dijital ürünler hakkında bilgi sunar. Siteyi kullanan ziyaretçi bu koşulları ve ilgili yasal politikaları kabul etmiş sayılır.</p>
<h2>2. Hizmet, paket ve fiyat bilgileri</h2>
<p>Sitedeki açıklamalar, teslim süreleri, paket kapsamları ve fiyatlar bilgilendirme ve teklif daveti niteliğindedir. Teklif formunun gönderilmesi tek başına sözleşme kurmaz. Bağlayıcı kapsam; tarafların yazılı olarak onayladığı teklif, sipariş bilgileri ve varsa mesafeli satış belgeleriyle belirlenir.</p>
<p>Vergiler, üçüncü taraf lisansları, alan adı, sunucu, reklam bütçesi veya kapsam dışı geliştirmeler, ilgili teklifte açıkça aksi yazmadıkça ayrıca değerlendirilebilir.</p>
<h2>3. Dijital teslimat ve müşteri yükümlülükleri</h2>
<p>Hizmetler elektronik ortamda teslim edilir; fiziksel ürün veya kargo gönderimi yapılmaz. Teslim süresi, ödemenin onaylanması ve proje için gerekli bilgi, içerik ve erişimlerin eksiksiz sağlanmasıyla başlar. Müşteri, paylaştığı içerik ve erişimlerin hukuka uygun olduğunu ve gerekli kullanım haklarına sahip bulunduğunu kabul eder.</p>
<h2>4. Fikri mülkiyet</h2>
<p>Sitenin tasarımı, metinleri, görselleri, markası ve yazılım bileşenleri ilgili hak sahiplerine aittir. Yazılı izin olmadan kopyalanamaz, yeniden yayımlanamaz veya ticari amaçla kullanılamaz.</p>
<p>Projeye özel kaynak kodu, tasarım ve diğer çıktıların kullanım veya devir kapsamı, ilgili teklif ve sözleşmede belirlenir. Üçüncü taraf açık kaynak bileşenleri kendi lisanslarına tabidir.</p>
<h2>5. Kabul edilebilir kullanım</h2>
<p>Siteye veya bağlı sistemlere zarar verme, güvenliği aşma, yetkisiz erişim denemesi, otomatik kötüye kullanım, hukuka aykırı içerik gönderme ve başkalarının haklarını ihlal etme yasaktır. Güvenlik riski oluşturan erişimler sınırlandırılabilir.</p>
<h2>6. Dış bağlantılar ve hizmetler</h2>
<p>Site üçüncü taraf sitelere veya hizmetlere bağlantı verebilir. Bu hizmetlerin içeriği, güvenliği ve koşulları kendi sağlayıcılarının sorumluluğundadır. Bir bağlantının bulunması, aksi açıkça belirtilmedikçe onay veya garanti anlamına gelmez.</p>
<h2>7. Sorumluluğun sınırı</h2>
<p>Site bilgilerinin güncel ve doğru tutulması için makul özen gösterilir. Bununla birlikte kesintisiz erişim, hatasız çalışma veya belirli bir ticari sonuç garanti edilmez. Emredici hukuk hükümleri saklı kalmak üzere sorumluluk, ilgili yazılı sözleşme ve uygulanabilir mevzuat çerçevesinde değerlendirilir.</p>
<h2>8. Değişiklik ve uygulanacak hukuk</h2>
<p>Bu koşullar hizmet veya mevzuat değişikliklerine göre güncellenebilir. Güncel sürüm bu sayfada yayımlanır. Koşullar Türkiye Cumhuriyeti hukukuna tabidir; tüketicilerin emredici mevzuattan doğan başvuru hakları saklıdır.</p>
<h2>9. İletişim</h2>
<p>Sorularınız için info@gzlteknoloji.com adresinden bize ulaşabilirsiniz.</p>','GZL Teknoloji internet sitesi, dijital hizmetler, paketler, fikri mülkiyet ve kabul edilebilir kullanım koşulları.','Kullanım Koşulları','GZL Teknoloji internet sitesi, dijital hizmetler, paketler, fikri mülkiyet ve kabul edilebilir kullanım koşulları.'),
  ('68806996-cbe4-4a15-bcc9-e8af733d266d','47000000-0000-4000-8000-000000000002','en','Terms of Use','terms','<p><strong>Effective date: 11 July 2026</strong></p>
<p>These terms govern use of gzlteknoloji.com, operated by <strong>GZL Danışmanlık Hizmetleri ve Teknoloji Ltd. Şti.</strong></p>
<h2>1. Scope</h2>
<p>The website provides information about software development, websites, e-commerce, automation, consulting, maintenance and digital products. Visitors using the website are subject to these terms and the related legal policies.</p>
<h2>2. Services, packages and prices</h2>
<p>Descriptions, delivery times, package scopes and prices on the website are informational and constitute an invitation to request a proposal. Submitting a form does not by itself create a contract. The binding scope is defined by the written proposal, order information and any applicable distance-sales documents approved by the parties.</p>
<p>Taxes, third-party licences, domains, servers, advertising budgets and out-of-scope development may be assessed separately unless the relevant proposal expressly states otherwise.</p>
<h2>3. Digital delivery and customer duties</h2>
<p>Services are delivered electronically; no physical goods are shipped. Delivery periods begin after payment confirmation and complete receipt of the information, content and access required for the project. Customers must ensure that supplied materials and access are lawful and properly authorised.</p>
<h2>4. Intellectual property</h2>
<p>The website design, text, media, brand and software components belong to their respective rights holders. They may not be copied, republished or commercially used without written permission.</p>
<p>Rights to project-specific source code, designs and deliverables are defined in the relevant proposal and contract. Third-party open-source components remain subject to their own licences.</p>
<h2>5. Acceptable use</h2>
<p>Users must not damage the website or connected systems, bypass security, attempt unauthorised access, perform automated abuse, submit unlawful content or infringe third-party rights. Access presenting a security risk may be restricted.</p>
<h2>6. External links and services</h2>
<p>The website may link to third-party services. Their content, security and terms are the responsibility of their providers. A link does not imply endorsement or warranty unless expressly stated.</p>
<h2>7. Limitation of responsibility</h2>
<p>Reasonable care is taken to keep website information accurate and current. Uninterrupted access, error-free operation or a particular commercial result is not guaranteed. Subject to mandatory law, responsibility is assessed under the applicable written agreement and legislation.</p>
<h2>8. Changes and governing law</h2>
<p>These terms may be updated when services or law changes. The current version is published here. Turkish law applies, without limiting mandatory consumer rights.</p>
<h2>9. Contact</h2>
<p>Questions may be sent to info@gzlteknoloji.com.</p>','Terms governing the GZL Technology website, digital services, packages, intellectual property and acceptable use.','Terms of Use','Terms governing the GZL Technology website, digital services, packages, intellectual property and acceptable use.'),
  ('7d77b64c-17cd-4947-b116-3141ecc9f48d','47000000-0000-4000-8000-000000000003','tr','Çerez Politikası','cookie-policy','<p><strong>Yürürlük tarihi: 11 Temmuz 2026</strong></p>
<p>Bu politika, gzlteknoloji.com sitesinde kullanılan çerezleri ve benzeri saklama teknolojilerini açıklar. Çerez, tarayıcınızda saklanan küçük bir veri kaydıdır.</p>
<h2>1. Çerez kategorileri</h2>
<p><strong>Zorunlu çerezler</strong>, sitenin güvenli çalışması ve tercihlerin hatırlanması için gereklidir. Bu çerezler kapatılamaz. <strong>Analitik çerezler</strong> ise ziyaretçilerin siteyi nasıl kullandığını anlamamıza yardımcı olur ve yalnızca onayınızla etkinleşir.</p>
<h2>2. Kullanılan çerezler</h2>
<div class="gm-table-scroll"><table><thead><tr><th scope="col">Çerez</th><th scope="col">Kategori</th><th scope="col">Sağlayıcı</th><th scope="col">Amaç</th><th scope="col">Süre</th></tr></thead><tbody><tr><td><code>site_cookie_consent_v1</code></td><td>Zorunlu</td><td>GZL Teknoloji</td><td>Çerez ve analitik tercihinizi hatırlamak</td><td>180 gün</td></tr><tr><td><code>_ga</code></td><td>Analitik</td><td>Google Analytics</td><td>Ziyaretçileri ayırt etmek</td><td>En fazla 2 yıl</td></tr><tr><td><code>_ga_<container-id></code></td><td>Analitik</td><td>Google Analytics</td><td>Oturum durumunu korumak</td><td>En fazla 2 yıl</td></tr></tbody></table></div>
<p>Analitik çerez adındaki container kimliği kullanılan Google Analytics ölçüm kimliğine göre değişir. Tarayıcılar çerez ömrünü daha kısa süreyle sınırlayabilir.</p>
<h2>3. Onayın yönetilmesi</h2>
<p>Analitik çerezler varsayılan olarak kapalıdır. Çerez bildirimindeki seçiminiz, zorunlu tercih çerezinde ve tarayıcınızın yerel depolama alanında 180 gün saklanır. Analitik onayını reddetmeniz sitenin temel işlevlerini engellemez.</p>
<p>Çerezleri tarayıcı ayarlarınızdan silebilir veya engelleyebilirsiniz. Zorunlu çerezin silinmesi hâlinde tercih ekranı yeniden gösterilebilir. Analitik tercihinizi çerez ayarları üzerinden değiştirebilirsiniz.</p>
<h2>4. Analitik ve veri aktarımı</h2>
<p>Analitik onayı verildiğinde Google Analytics 4 ve Google Tag Manager kullanılabilir. Bu araçlarla elde edilen cihaz ve kullanım verileri Google tarafından yurt dışında işlenebilir. Ayrıntılar için Gizlilik Politikası’nı inceleyebilirsiniz.</p>
<h2>5. Güncellemeler ve iletişim</h2>
<p>Kullanılan araçlar veya mevzuat değiştiğinde bu politika güncellenir. Sorularınız için info@gzlteknoloji.com adresinden bize ulaşabilirsiniz.</p>','GZL Teknoloji sitesinde kullanılan zorunlu ve analitik çerezler, kullanım amaçları, süreleri ve tercih yönetimi.','Çerez Politikası','GZL Teknoloji sitesinde kullanılan zorunlu ve analitik çerezler, kullanım amaçları, süreleri ve tercih yönetimi.'),
  ('54505323-dc8b-4d56-b240-9d8e6d1f072c','47000000-0000-4000-8000-000000000003','en','Cookie Policy','cookie-policy','<p><strong>Effective date: 11 July 2026</strong></p>
<p>This policy explains cookies and similar storage technologies used on gzlteknoloji.com. A cookie is a small data record stored by your browser.</p>
<h2>1. Cookie categories</h2>
<p><strong>Necessary cookies</strong> support secure operation and remember preferences. They cannot be disabled through the website. <strong>Analytics cookies</strong> help us understand website use and are activated only with consent.</p>
<h2>2. Cookies used</h2>
<div class="gm-table-scroll"><table><thead><tr><th scope="col">Cookie</th><th scope="col">Category</th><th scope="col">Provider</th><th scope="col">Purpose</th><th scope="col">Duration</th></tr></thead><tbody><tr><td><code>site_cookie_consent_v1</code></td><td>Necessary</td><td>GZL Technology</td><td>Remember cookie and analytics preferences</td><td>180 days</td></tr><tr><td><code>_ga</code></td><td>Analytics</td><td>Google Analytics</td><td>Distinguish users</td><td>Up to 2 years</td></tr><tr><td><code>_ga_<container-id></code></td><td>Analytics</td><td>Google Analytics</td><td>Persist session state</td><td>Up to 2 years</td></tr></tbody></table></div>
<p>The container identifier in the analytics cookie name depends on the active Google Analytics measurement identifier. Browsers may enforce shorter lifetimes.</p>
<h2>3. Managing consent</h2>
<p>Analytics cookies are disabled by default. Your choice is stored in the necessary preference cookie and browser local storage for 180 days. Refusing analytics does not prevent essential website functions.</p>
<p>Cookies may also be deleted or blocked in browser settings. Deleting the necessary preference cookie may cause the consent interface to appear again. Analytics preferences may be changed through cookie settings.</p>
<h2>4. Analytics and transfers</h2>
<p>Where analytics consent is given, Google Analytics 4 and Google Tag Manager may be used. Device and usage data may be processed by Google outside Türkiye. See the Privacy Policy for further information.</p>
<h2>5. Updates and contact</h2>
<p>This policy is updated when tools or applicable law changes. Questions may be sent to info@gzlteknoloji.com.</p>','Necessary and analytics cookies used by GZL Technology, their purposes, duration and preference controls.','Cookie Policy','Necessary and analytics cookies used by GZL Technology, their purposes, duration and preference controls.')
ON DUPLICATE KEY UPDATE title=VALUES(title),slug=VALUES(slug),content=VALUES(content),summary=VALUES(summary),meta_title=VALUES(meta_title),meta_description=VALUES(meta_description);
