-- =============================================================
-- FILE: content/gzl/904_gzl_ui_sections.sql
-- OTOMATIK URETILDI — backend/scripts/generate-gzl-ui-sections.mjs
--
-- Hizmetler / portfolyo / blog / markalar / yorumlar / is birligi
-- bolumlerinin ARAYUZ METINLERI (tr, en, de).
--
-- Sablon etiketleri ("Yukleniyor...", "Tumunu Gor", "3 dk okuma") GWD
-- surumunden devralindi — bunlar markaya degil sablona ait.
-- Baslik/tanitim/ornek kart gibi MARKA metinleri GZL icin yeniden yazildi.
-- Uretim sonunda cikti GWD izlerine karsi taranir; sizinti varsa script
-- dosyayi YAZMAZ.
--
-- Yeniden uretmek icin:
--   node backend/scripts/generate-gzl-ui-sections.mjs
-- =============================================================

SET NAMES utf8mb4;

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('3c4789ce-0713-4929-8eaf-dd771f7764f2', 'ui_services', 'tr', '{"page":{"badge":"Hizmetlerimiz","title_html":"İşinizi <span class=\\"text-300\\">yazılımla</span> ölçülebilir biçimde ileri taşıyoruz","intro_html":"Kurumsal web ve e-ticaretten ERP, CRM ve otomasyon panellerine kadar üretime hazır sistemler geliştiriyoruz. Her teklif; kapsamı, teslim süresini ve revizyon hakkını yazılı olarak içerir.","tagline_fallback":"Yaratıcı. Özgün. Gerçek.","card_fallback_title":"Başlıksız","loading":"Yükleniyor...","error":"Hizmetler yüklenemedi.","empty":"Hizmet bulunamadı.","highlight_label":"Öne Çıkan","details_label":"Detaylar"},"section1":{"heading":"Hizmetlerimiz","intro_html":"Özel yazılım, kurumsal web ve e-ticaret, otomasyon, yapay zekâ entegrasyonu ve GEO/SEO danışmanlığı.","error":"Hizmetler yüklenemedi.","cta_label":"Teklif Al","empty":"Hizmet bulunamadı.","loading_title":"Yükleniyor...","loading_text":"Lütfen bekleyin","card_fallback_title":"Başlıksız"},"section2":{"badge":"Hizmetler","title_html":"Ne <span class=\\"text-300\\">yapıyoruz</span>","error":"Hizmetler yüklenemedi.","learn_more":"Detaylar","empty":"Hizmet bulunamadı.","loading_title":"Yükleniyor...","loading_text":"Lütfen bekleyin","card_fallback_title":"Başlıksız","footer_text_html":"Aradığınız hizmeti göremediniz mi?","footer_link_label":"İletişime geç!"},"detail":{"back_label":"Hizmetlere Dön","loading":"Yükleniyor...","error":"Hizmet yüklenemedi.","highlight_label":"Öne Çıkan","details_label":"Detaylar","description_label":"Açıklama","gallery_label":"Galeri","gallery_loading":"Yükleniyor...","gallery_empty":"Galeride görsel yok.","not_found":"Hizmet bulunamadı.","title_fallback":"Hizmet","tagline_fallback":"Yaratıcı. Özgün. Gerçek."}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('9bf72d88-a4ec-46e6-8d14-4ad1ac14765c', 'ui_project', 'tr', '{"projects1":{"heading":"Son Projelerimiz","intro_html":"Tasarımdan canlıya almaya kadar aynı ekibin yürüttüğü, üretimde çalışan işler.","cta_label":"Tüm Projeleri Gör","cta_short_label":"Tümünü Gör"},"projects2":{"badge":"Projeler","heading":"Son Projelerimiz","slide_title_html":"Üretimde çalışan <span class=\\"text-300\\">işler</span>","slide_description":"Kurumsal siteler, e-ticaret platformları ve SaaS panelleri.","info_label":"Proje Bilgisi","client_label":"Müşteri","completion_label":"Tamamlanma Süresi","technologies_label":"Teknolojiler","live_demo_label":"Canlı Demo","github_label":"GitHub''da Gör","sample_client":"Ensotek","sample_completion":"2026","sample_technologies":"Next.js, Fastify, MySQL"},"work":{"badge":"Portfolyo","title_html":"Kanıtlanabilir <span class=\\"text-300\\">işler</span>","intro_html":"Portfolyomuzda 21 tamamlanmış proje yer alıyor; bir bölümü hâlâ canlıda çalışıyor.","loading_title":"Yükleniyor...","label_client":"Müşteri","label_completion_time":"Tamamlanma Süresi","label_tools":"Araçlar","updating":"Güncelleniyor...","empty_title":"Proje bulunamadı","empty_text":"Lütfen admin panelinden proje ekleyin."},"detail":{"loading":"Yükleniyor...","not_found":"Bulunamadı","slug_prefix":"slug:","slug_missing":"slug yok","badge":"proje detayları","label_client":"Müşteri","label_start":"Başlangıç","label_complete":"Bitiş","label_services":"Hizmetler","label_website":"Web Sitesi","description_label":"Açıklama","tools_label":"Araçlar","key_features_label":"Öne Çıkan Özellikler","technologies_used_label":"Kullanılan Teknolojiler","design_highlights_label":"Tasarım Öne Çıkanları","details_label":"Detaylar","gallery_label":"Galeri","case_study_title":"Vaka çalışması","case_study_challenge_label":"Challenge","case_study_approach_label":"Yaklaşım","case_study_outcome_label":"Sonuç"}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('b166ba7b-4e07-429e-8f8c-5be5abf0cbbe', 'ui_blog', 'tr', '{"blog1":{"heading":"Blog","intro":"Yazılım, otomasyon ve yapay zekâ aramaları üzerine notlarımız","cta_label":"Daha fazlası","loading":"Yükleniyor...","error":"Bir şeyler ters gitti.","empty":"Yazı bulunamadı.","read_time":"3 dk okuma","category_fallback":"Blog"},"blog2":{"badge":"Son Yazılar","heading":"Blog","card1_category":"GEO","card1_title":"GEO nedir, neden önemli?","card1_description":"Yapay zekâ aramalarında görünürlük.","card2_category":"E-ticaret","card2_title":"E-ticaret sitesi maliyeti","card2_description":"Kalemler ve gerçekçi bütçe.","card3_category":"Otomasyon","card3_title":"Elle yapılan 5 iş","card3_description":"Otomasyona uygun süreçler.","sample_date":"28 Mart 2026","read_time":"3 dk okuma"},"list":{"badge":"Blog","title_html":"Yazılım ve <span class=\\"text-300\\">dijital dönüşüm</span> notları","intro_html":"GEO/SEO, e-ticaret maliyetleri, iş otomasyonu ve yapay zekâ üzerine yazılar.","loading":"Yükleniyor...","error":"Yazılar yüklenemedi.","read_time":"3 dk okuma","default_category":"Blog","empty":"Yazı bulunamadı."},"post":{"loading":"Yükleniyor...","error":"Bir hata oluştu","empty":"Yazı bulunamadı"},"detail":{"loading_title":"Yükleniyor...","loading_text":"Lütfen bekleyin","not_found_title":"Yazı bulunamadı","not_found_text_prefix":"Geçersiz slug:","error_title":"Bir hata oluştu","error_text":"Lütfen tekrar deneyin.","read_time_label":"16 dk okuma","by_label":"Yazar","share_label":"Paylaş","related_title":"İlgili yazılar","view_more_label":"Daha fazlası","related_empty":"İlgili yazı bulunamadı.","category_fallback":"Blog","read_time":"3 dk okuma","author_section_title":"Yazar","author_bio_html":"<p>GZL Teknoloji — Gemlik/Bursa merkezli yazılım ve dijital danışmanlık şirketi.</p>"}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('66bc37d1-06d5-4695-8082-0b63a33e6d6f', 'ui_brands', 'tr', '{"heading":"Çalıştığımız teknolojiler","intro_html":"Projelerimizde kullandığımız üretim araçları ve platformlar.","track":"right","loading":"Yükleniyor...","error":"Markalar yüklenemedi.","empty":"Marka bulunamadı."}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('a798879c-e09e-492c-8899-4631c1c4b04b', 'ui_testimonials', 'tr', '{"headline":"Müşteri Yorumları","intro_line_1":"Bionluk üzerindeki hizmet geçmişimizde","intro_line_2":"16 tamamlanmış sipariş ve 4,50/5 değerlendirme puanı bulunuyor.","target_type":"testimonial","bucket":"11111111-1111-1111-1111-111111111111","cta_label":"","cta_href":"#","loading":"Yükleniyor...","error":"Yorumlar yüklenemedi.","empty":"Henüz yorum yok.","man_img":"/uploads/site-media/logo_transparent.png","decorate_img":""}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('9920a1b5-c7de-448e-8c0e-f17d4bf351b8', 'ui_coporation', 'tr', '{"badge":"İş Birliği","heading_html":"<span class=\\"text-300\\">21 tamamlanmış proje</span><br /> teslim edildi_","contact":{"avatar":"/uploads/site-media/logo_transparent.png","avatar_alt":"GZL Teknoloji","skype_label":"[skype]","skype_value":"","skype_href":"","phone_label":"[telefon]","phone_value":"","phone_href":"","email_label":"[eposta]","email_value":"info@gzlteknoloji.com","email_href":"mailto:info@gzlteknoloji.com"},"journal":{"badge":"Git Günlüğü","items":[{"date":"15 Tem:","title":"Muzzilla-streaming-API-services-for-Python"},{"date":"30 Haz:","title":"ChatHub-Chat-application-VueJs-Mongodb"},{"date":"26 May:","title":"DineEasy-coffee-tea-reservation-system"},{"date":"17 Nis:","title":"FinanceBuddy-Personal-finance-tracker"},{"date":"05 Mar:","title":"TuneStream-Music-streaming-service-API"}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('034e576d-a951-41ce-82b0-c2d5561550e4', 'ui_skills', 'tr', '{"skills1":{"heading":"Uzmanlıklarımız","intro_html":"Kullandığımız teknolojiler ve üretim araçları.","loading":"Yükleniyor...","error":"Yetenekler yüklenemedi.","empty":"Yetenek bulunamadı.","extra_intro":"Ayrıca şu alanlarda çalışıyoruz:","extra_items":["HTML","CSS","Javascript","Bootstrap","TailwindCSS"]},"skills2":{"badge":"Uzmanlıklar","heading":"Uzmanlıklarımız","loading":"Yükleniyor...","error":"Yüklenemedi.","list_items":[{"label":"Ön Yüz:","value":"HTML, CSS, JavaScript, React, Angular"},{"label":"Arka Uç:","value":"Node.js, Express, Python, Django"},{"label":"Veritabanları:","value":"MySQL, PostgreSQL, MongoDB"},{"label":"Araçlar ve Platformlar:","value":"Git, Docker, AWS, Heroku"},{"label":"Diğerleri:","value":"RESTful API''ler, GraphQL, Agile Metodolojiler"}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('74087c91-8365-4c27-8a5f-3a0801a46900', 'ui_resume', 'tr', '{"resume1":{"heading":"Deneyimimiz","intro_html":"Kurumsal web ve e-ticaret, ERP/CRM panelleri, otomasyon ve yapay zekâ entegrasyonu alanlarında üretime alınmış işler.","cta_label":"İletişime geçin","education_label":"Eğitim","experience_label":"Deneyim","loading":"Yükleniyor...","error":"Özgeçmiş verileri yüklenemedi.","empty_education":"Eğitim kaydı bulunamadı.","empty_experience":"Deneyim kaydı bulunamadı.","marquee_text":"Next.js . Fastify . MySQL . Drizzle"},"education2":{"heading":"Eğitim","loading_label":"Yükleniyor...","loading_text":"Lütfen bekleyin","error_label":"Başarısız","error_text":"Eğitim verileri yüklenemedi.","empty_label":"Kayıt yok","empty_text":"Eğitim kaydı bulunamadı.","research_heading":"Araştırmalar","research_items":[{"year":"2023-2024:","title":"Büyük Veri Araçlarıyla Gelişmiş Veri Analitiği","description":"Gelişmiş analizler ve içgörüler için büyük veri araçları kullanıldı."},{"year":"2021-2013:","title":"Bulut Yerel Uygulama Mimarileri","description":"Bulut yerel uygulamaları tasarlamak için en iyi uygulamalar incelendi."},{"year":"2019-2020:","title":"Yapay Zeka Destekli Kullanıcı Deneyimi Kişiselleştirme","description":"Davranışlara göre kullanıcı deneyimini kişiselleştirmek için yapay zeka kullanıldı."}]},"experience2":{"heading":"Eğitim","loading_label":"Yükleniyor...","loading_text":"Lütfen bekleyin","error_label":"Başarısız","error_text":"Eğitim verileri yüklenemedi.","empty_label":"Kayıt yok","empty_text":"Eğitim kaydı bulunamadı.","research_heading":"Araştırmalar","research_items":[{"year":"2023-2024:","title":"Büyük Veri Araçlarıyla Gelişmiş Veri Analitiği","description":"Gelişmiş analizler ve içgörüler için büyük veri araçları kullanıldı."},{"year":"2021-2013:","title":"Bulut Yerel Uygulama Mimarileri","description":"Bulut yerel uygulamaları tasarlamak için en iyi uygulamalar incelendi."},{"year":"2019-2020:","title":"Yapay Zeka Destekli Kullanıcı Deneyimi Kişiselleştirme","description":"Davranışlara göre kullanıcı deneyimini kişiselleştirmek için yapay zeka kullanıldı."}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('c275b723-cea7-47f3-84f4-11638a0729ee', 'ui_services', 'en', '{"page":{"badge":"Our Services","title_html":"We move your business forward with <span class=\\"text-300\\">software</span> that is measurable","intro_html":"From corporate web and e-commerce to ERP, CRM and automation panels, we build production-ready systems. Every proposal states scope, delivery time and revision rights in writing.","tagline_fallback":"Creative. Unique. Reality.","card_fallback_title":"Untitled","loading":"Loading...","error":"Failed to load services.","empty":"No services found.","highlight_label":"Highlight","details_label":"Details"},"section1":{"heading":"Our Services","intro_html":"Custom software, corporate web and e-commerce, automation, AI integration and GEO/SEO consulting.","error":"Failed to load services.","cta_label":"Get a Quote","empty":"No services found.","loading_title":"Loading...","loading_text":"Please wait","card_fallback_title":"Untitled"},"section2":{"badge":"Services","title_html":"What we <span class=\\"text-300\\">do</span>","error":"Failed to load services.","learn_more":"Learn more","empty":"No services found.","loading_title":"Loading...","loading_text":"Please wait","card_fallback_title":"Untitled","footer_text_html":"Cannot find the service you need?","footer_link_label":"Reach out!"},"detail":{"back_label":"Back to Services","loading":"Loading...","error":"Failed to load service.","highlight_label":"Highlight","details_label":"Details","description_label":"Description","gallery_label":"Gallery","gallery_loading":"Loading...","gallery_empty":"No gallery images.","not_found":"Service not found.","title_fallback":"Service","tagline_fallback":"Creative. Unique. Reality."}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('2839a8cb-0f81-4ff2-8f33-775a3cfbb480', 'ui_project', 'en', '{"projects1":{"heading":"Our Latest Work","intro_html":"Work running in production, delivered end to end by the same team.","cta_label":"View All Projects","cta_short_label":"View All"},"projects2":{"badge":"Projects","heading":"Our Latest Work","slide_title_html":"Work running in <span class=\\"text-300\\">production</span>","slide_description":"Corporate sites, e-commerce platforms and SaaS panels.","info_label":"Project Info","client_label":"Client","completion_label":"Completion Time","technologies_label":"Technologies","live_demo_label":"Live Demo","github_label":"View on Github","sample_client":"Ensotek","sample_completion":"2026","sample_technologies":"Next.js, Fastify, MySQL"},"work":{"badge":"Portfolio","title_html":"Verifiable <span class=\\"text-300\\">work</span>","intro_html":"Our portfolio holds 21 completed projects, several of them still live.","loading_title":"Loading...","label_client":"Client","label_completion_time":"Completion Time","label_tools":"Tools","updating":"Updating...","empty_title":"No projects found","empty_text":"Please add projects from admin panel."},"detail":{"loading":"Loading...","not_found":"Not found","slug_prefix":"slug:","slug_missing":"slug missing","badge":"work details","label_client":"Client","label_start":"Start","label_complete":"Complete","label_services":"Services","label_website":"Website","description_label":"Description","tools_label":"Tools","key_features_label":"Key Features","technologies_used_label":"Technologies Used","design_highlights_label":"Design Highlights","details_label":"Details","gallery_label":"Gallery","case_study_title":"Case study","case_study_challenge_label":"Challenge","case_study_approach_label":"Approach","case_study_outcome_label":"Outcome"}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('ee939961-d9c4-4493-807c-50803dfb3539', 'ui_blog', 'en', '{"blog1":{"heading":"Blog","intro":"Our notes on software, automation and AI search","cta_label":"View more","loading":"Loading...","error":"Something went wrong.","empty":"No posts found.","read_time":"3 min read","category_fallback":"Blog"},"blog2":{"badge":"Latest Posts","heading":"Blog","card1_category":"GEO","card1_title":"What is GEO and why does it matter?","card1_description":"Visibility in AI-powered search.","card2_category":"E-commerce","card2_title":"What an e-commerce site costs","card2_description":"Line items and a realistic budget.","card3_category":"Automation","card3_title":"Five tasks still done by hand","card3_description":"Processes ready for automation.","sample_date":"March 28, 2026","read_time":"3 min read"},"list":{"badge":"Blog","title_html":"Notes on software and <span class=\\"text-300\\">digital transformation</span>","intro_html":"Articles on GEO/SEO, e-commerce costs, business automation and AI.","loading":"Loading...","error":"Failed to load posts.","read_time":"3 min read","default_category":"Blog","empty":"No posts found."},"post":{"loading":"Loading...","error":"Something went wrong","empty":"No Posts Found"},"detail":{"loading_title":"Loading...","loading_text":"Please wait","not_found_title":"Post not found","not_found_text_prefix":"Invalid slug:","error_title":"Something went wrong","error_text":"Please try again.","read_time_label":"16 mins to read","by_label":"By","share_label":"Share","related_title":"Related posts","view_more_label":"View more","related_empty":"No related posts.","category_fallback":"Blog","read_time":"3 min read","author_section_title":"Author","author_bio_html":"<p>GZL Technology — software and digital consulting company based in Gemlik/Bursa, Türkiye.</p>"}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('d030fd76-d8ca-4883-8765-3b92eea6e10c', 'ui_brands', 'en', '{"heading":"Technologies we work with","intro_html":"The production tools and platforms we use across our projects.","track":"right","loading":"Loading...","error":"Failed to load brands.","empty":"No brands found."}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('d96abd6f-6663-408a-8185-06a64d5b4a11', 'ui_testimonials', 'en', '{"headline":"Client Reviews","intro_line_1":"Our service record on Bionluk shows","intro_line_2":"16 completed orders and a 4.50/5 rating.","target_type":"testimonial","bucket":"11111111-1111-1111-1111-111111111111","cta_label":"","cta_href":"#","loading":"Loading...","error":"Failed to load testimonials.","empty":"No testimonials yet.","man_img":"/uploads/site-media/logo_transparent.png","decorate_img":""}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('7bd11504-0ee0-479f-810b-86812f757d2e', 'ui_coporation', 'en', '{"badge":"Collaboration","heading_html":"<span class=\\"text-300\\">21 completed projects</span><br /> delivered_","contact":{"avatar":"/uploads/site-media/logo_transparent.png","avatar_alt":"GZL Technology","skype_label":"[skype]","skype_value":"","skype_href":"","phone_label":"[phone]","phone_value":"","phone_href":"","email_label":"[email]","email_value":"info@gzlteknoloji.com","email_href":"mailto:info@gzlteknoloji.com"},"journal":{"badge":"Git Journaling","items":[{"date":"15 Jul:","title":"Muzzilla-streaming-API-services-for-Python"},{"date":"30 Jun:","title":"ChatHub-Chat-application-VueJs-Mongodb"},{"date":"26 May:","title":"DineEasy-coffee-tea-reservation-system"},{"date":"17 Apr:","title":"FinanceBuddy-Personal-finance-tracker"},{"date":"05 Mar:","title":"TuneStream-Music-streaming-service-API"}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('4d288c5d-593f-4e89-870a-c579a3bc55f0', 'ui_skills', 'en', '{"skills1":{"heading":"Our Expertise","intro_html":"The technologies and production tools we use.","loading":"Loading...","error":"Failed to load skills.","empty":"No skills found.","extra_intro":"We also work with:","extra_items":["HTML","CSS","Javascript","Bootstrap","TailwindCSS"]},"skills2":{"badge":"Expertise","heading":"Our Expertise","loading":"Loading...","error":"Failed to load.","list_items":[{"label":"Front-End:","value":"HTML, CSS, JavaScript, React, Angular"},{"label":"Back-End:","value":"Node.js, Express, Python, Django"},{"label":"Databases:","value":"MySQL, PostgreSQL, MongoDB"},{"label":"Tools & Platforms:","value":"Git, Docker, AWS, Heroku"},{"label":"Others:","value":"RESTful APIs, GraphQL, Agile Methodologies"}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('b1ceba26-375c-4cf2-8c30-62d59fe47837', 'ui_resume', 'en', '{"resume1":{"heading":"Our Experience","intro_html":"Work delivered to production across corporate web and e-commerce, ERP/CRM panels, automation and AI integration.","cta_label":"Get in touch","education_label":"Education","experience_label":"Experience","loading":"Loading...","error":"Failed to load resume data.","empty_education":"No education entries found.","empty_experience":"No experience entries found.","marquee_text":"Next.js . Fastify . MySQL . Drizzle"},"education2":{"heading":"Education","loading_label":"Loading...","loading_text":"Please wait","error_label":"Failed","error_text":"Education data could not be loaded.","empty_label":"No entries","empty_text":"No education entries found.","research_heading":"Researched","research_items":[{"year":"2023-2024:","title":"Advanced Data Analytics with Big Data Tools","description":"Utilized big data tools for advanced analytics and insights."},{"year":"2021-2013:","title":"Cloud-Native Application Architectures","description":"Studied best practices for designing cloud-native applications."},{"year":"2019-2020:","title":"AI-Driven User Experience Personalization","description":"Leveraged AI to personalize user experiences based on behavior."}]},"experience2":{"heading":"Education","loading_label":"Loading...","loading_text":"Please wait","error_label":"Failed","error_text":"Education data could not be loaded.","empty_label":"No entries","empty_text":"No education entries found.","research_heading":"Researched","research_items":[{"year":"2023-2024:","title":"Advanced Data Analytics with Big Data Tools","description":"Utilized big data tools for advanced analytics and insights."},{"year":"2021-2013:","title":"Cloud-Native Application Architectures","description":"Studied best practices for designing cloud-native applications."},{"year":"2019-2020:","title":"AI-Driven User Experience Personalization","description":"Leveraged AI to personalize user experiences based on behavior."}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('4ea2cbf5-c96a-4217-8125-00109ec4d1ee', 'ui_services', 'de', '{"page":{"badge":"Unsere Leistungen","title_html":"Wir bringen Ihr Unternehmen mit <span class=\\"text-300\\">Software</span> messbar voran","intro_html":"Von Unternehmenswebsites und E-Commerce bis zu ERP-, CRM- und Automatisierungspanels bauen wir produktionsreife Systeme. Jedes Angebot nennt Umfang, Lieferzeit und Revisionsrechte schriftlich.","tagline_fallback":"Kreativ. Einzigartig. Echt.","card_fallback_title":"Ohne Titel","loading":"Wird geladen...","error":"Services konnten nicht geladen werden.","empty":"Keine Services gefunden.","highlight_label":"Highlight","details_label":"Details"},"section1":{"heading":"Unsere Leistungen","intro_html":"Individuelle Software, Unternehmenswebsites und E-Commerce, Automatisierung, KI-Integration und GEO/SEO-Beratung.","error":"Services konnten nicht geladen werden.","cta_label":"Angebot anfordern","empty":"Keine Services gefunden.","loading_title":"Wird geladen...","loading_text":"Bitte warten","card_fallback_title":"Ohne Titel"},"section2":{"badge":"Leistungen","title_html":"Was wir <span class=\\"text-300\\">tun</span>","error":"Services konnten nicht geladen werden.","learn_more":"Mehr erfahren","empty":"Keine Services gefunden.","loading_title":"Wird geladen...","loading_text":"Bitte warten","card_fallback_title":"Ohne Titel","footer_text_html":"Die gesuchte Leistung nicht gefunden?","footer_link_label":"Kontakt aufnehmen!"},"detail":{"back_label":"Zurück zu Services","loading":"Wird geladen...","error":"Service konnte nicht geladen werden.","highlight_label":"Highlight","details_label":"Details","description_label":"Beschreibung","gallery_label":"Galerie","gallery_loading":"Wird geladen...","gallery_empty":"Keine Galeriebilder.","not_found":"Service nicht gefunden.","title_fallback":"Service","tagline_fallback":"Kreativ. Einzigartig. Echt."}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('dd9e0990-99da-495d-8d37-763d2d822dbc', 'ui_project', 'de', '{"projects1":{"heading":"Unsere neuesten Projekte","intro_html":"Projekte im Produktivbetrieb, vom Entwurf bis zum Livegang aus einer Hand.","cta_label":"Alle Projekte anzeigen","cta_short_label":"Alle anzeigen"},"projects2":{"badge":"Projekte","heading":"Unsere neuesten Projekte","slide_title_html":"Projekte im <span class=\\"text-300\\">Produktivbetrieb</span>","slide_description":"Unternehmenswebsites, E-Commerce-Plattformen und SaaS-Panels.","info_label":"Projektinfo","client_label":"Kunde","completion_label":"Fertigstellungszeit","technologies_label":"Technologien","live_demo_label":"Live-Demo","github_label":"Auf GitHub ansehen","sample_client":"Ensotek","sample_completion":"2026","sample_technologies":"Next.js, Fastify, MySQL"},"work":{"badge":"Portfolio","title_html":"Nachweisbare <span class=\\"text-300\\">Projekte</span>","intro_html":"Unser Portfolio umfasst 21 abgeschlossene Projekte, mehrere davon weiterhin live.","loading_title":"Wird geladen...","label_client":"Kunde","label_completion_time":"Fertigstellungszeit","label_tools":"Tools","updating":"Aktualisiere...","empty_title":"Keine Projekte gefunden","empty_text":"Bitte Projekte im Admin-Panel hinzufügen."},"detail":{"loading":"Wird geladen...","not_found":"Nicht gefunden","slug_prefix":"slug:","slug_missing":"slug fehlt","badge":"Projekt-Details","label_client":"Kunde","label_start":"Start","label_complete":"Fertig","label_services":"Leistungen","label_website":"Website","description_label":"Beschreibung","tools_label":"Tools","key_features_label":"Hauptfunktionen","technologies_used_label":"Verwendete Technologien","design_highlights_label":"Design-Highlights","details_label":"Details","gallery_label":"Galerie","case_study_title":"Fallstudie","case_study_challenge_label":"Challenge","case_study_approach_label":"Vorgehen","case_study_outcome_label":"Ergebnis"}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('e2b13e9d-4b8d-48d0-8898-401de9312b23', 'ui_blog', 'de', '{"blog1":{"heading":"Blog","intro":"Unsere Notizen zu Software, Automatisierung und KI-Suche","cta_label":"Mehr anzeigen","loading":"Wird geladen...","error":"Etwas ist schiefgelaufen.","empty":"Keine Beiträge gefunden.","read_time":"3 Min. Lesezeit","category_fallback":"Blog"},"blog2":{"badge":"Neueste Beiträge","heading":"Blog","card1_category":"GEO","card1_title":"Was ist GEO und warum ist es wichtig?","card1_description":"Sichtbarkeit in KI-gestützter Suche.","card2_category":"E-Commerce","card2_title":"Was eine E-Commerce-Website kostet","card2_description":"Posten und ein realistisches Budget.","card3_category":"Automatisierung","card3_title":"Fünf Aufgaben, die noch manuell laufen","card3_description":"Prozesse, die sich automatisieren lassen.","sample_date":"28. März 2026","read_time":"3 Min. Lesezeit"},"list":{"badge":"Blog","title_html":"Notizen zu Software und <span class=\\"text-300\\">digitaler Transformation</span>","intro_html":"Artikel zu GEO/SEO, E-Commerce-Kosten, Prozessautomatisierung und KI.","loading":"Wird geladen...","error":"Beiträge konnten nicht geladen werden.","read_time":"3 Min. Lesezeit","default_category":"Blog","empty":"Keine Beiträge gefunden."},"post":{"loading":"Wird geladen...","error":"Etwas ist schiefgelaufen","empty":"Keine Beiträge gefunden"},"detail":{"loading_title":"Wird geladen...","loading_text":"Bitte warten","not_found_title":"Beitrag nicht gefunden","not_found_text_prefix":"Ungültiger Slug:","error_title":"Etwas ist schiefgelaufen","error_text":"Bitte versuche es erneut.","read_time_label":"16 Min. Lesezeit","by_label":"Von","share_label":"Teilen","related_title":"Ähnliche Beiträge","view_more_label":"Mehr anzeigen","related_empty":"Keine ähnlichen Beiträge.","category_fallback":"Blog","read_time":"3 Min. Lesezeit","author_section_title":"Autor","author_bio_html":"<p>GZL Technologie — Software- und Digitalberatung mit Sitz in Gemlik/Bursa, Türkei.</p>"}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('7f5c7e4f-cbb3-464f-8282-e4b3682711f7', 'ui_brands', 'de', '{"heading":"Technologien, mit denen wir arbeiten","intro_html":"Die Produktionswerkzeuge und Plattformen, die wir in unseren Projekten einsetzen.","track":"right","loading":"Wird geladen...","error":"Marken konnten nicht geladen werden.","empty":"Keine Marken gefunden."}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('6b7411fd-70fe-481a-845b-6540d69d8963', 'ui_testimonials', 'de', '{"headline":"Kundenbewertungen","intro_line_1":"Unsere Servicebilanz auf Bionluk zeigt","intro_line_2":"16 abgeschlossene Bestellungen und eine Bewertung von 4,50/5.","target_type":"testimonial","bucket":"11111111-1111-1111-1111-111111111111","cta_label":"","cta_href":"#","loading":"Wird geladen...","error":"Testimonials konnten nicht geladen werden.","empty":"Noch keine Testimonials.","man_img":"/uploads/site-media/logo_transparent.png","decorate_img":""}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('40559d0f-faab-4780-8617-58d6883be0f5', 'ui_coporation', 'de', '{"badge":"Zusammenarbeit","heading_html":"<span class=\\"text-300\\">21 abgeschlossene Projekte</span><br /> geliefert_","contact":{"avatar":"/uploads/site-media/logo_transparent.png","avatar_alt":"GZL Technologie","skype_label":"[skype]","skype_value":"","skype_href":"","phone_label":"[telefon]","phone_value":"","phone_href":"","email_label":"[email]","email_value":"info@gzlteknoloji.com","email_href":"mailto:info@gzlteknoloji.com"},"journal":{"badge":"Git Journal","items":[{"date":"15 Jul:","title":"Muzzilla-streaming-API-services-for-Python"},{"date":"30 Jun:","title":"ChatHub-Chat-application-VueJs-Mongodb"},{"date":"26 Mai:","title":"DineEasy-coffee-tea-reservation-system"},{"date":"17 Apr:","title":"FinanceBuddy-Personal-finance-tracker"},{"date":"05 Mär:","title":"TuneStream-Music-streaming-service-API"}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('458f5c26-ee7e-43f9-84bc-ee1d17fbd5de', 'ui_skills', 'de', '{"skills1":{"heading":"Unsere Kompetenzen","intro_html":"Die Technologien und Werkzeuge, die wir einsetzen.","loading":"Wird geladen...","error":"Skills konnten nicht geladen werden.","empty":"Keine Skills gefunden.","extra_intro":"Wir arbeiten ausserdem mit:","extra_items":["HTML","CSS","JavaScript","Bootstrap","TailwindCSS"]},"skills2":{"badge":"Kompetenzen","heading":"Unsere Kompetenzen","loading":"Wird geladen...","error":"Konnte nicht geladen werden.","list_items":[{"label":"Front-End:","value":"HTML, CSS, JavaScript, React, Angular"},{"label":"Back-End:","value":"Node.js, Express, Python, Django"},{"label":"Datenbanken:","value":"MySQL, PostgreSQL, MongoDB"},{"label":"Tools & Plattformen:","value":"Git, Docker, AWS, Heroku"},{"label":"Sonstiges:","value":"RESTful APIs, GraphQL, Agile Methodologien"}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
  ('88a43cee-d632-4f48-8e15-babe5ed1f31c', 'ui_resume', 'de', '{"resume1":{"heading":"Unsere Erfahrung","intro_html":"In den Produktivbetrieb gebrachte Projekte in Unternehmenswebsites und E-Commerce, ERP/CRM-Panels, Automatisierung und KI-Integration.","cta_label":"Kontakt aufnehmen","education_label":"Ausbildung","experience_label":"Erfahrung","loading":"Wird geladen...","error":"Lebenslaufdaten konnten nicht geladen werden.","empty_education":"Keine Ausbildungseinträge gefunden.","empty_experience":"Keine Erfahrungseinträge gefunden.","marquee_text":"Next.js . Fastify . MySQL . Drizzle"},"education2":{"heading":"Ausbildung","loading_label":"Wird geladen...","loading_text":"Bitte warten","error_label":"Fehlgeschlagen","error_text":"Ausbildungsdaten konnten nicht geladen werden.","empty_label":"Keine Einträge","empty_text":"Keine Ausbildungseinträge gefunden.","research_heading":"Recherchiert","research_items":[{"year":"2023-2024:","title":"Erweiterte Datenanalyse mit Big-Data-Tools","description":"Big-Data-Tools für fortgeschrittene Analysen und Einblicke eingesetzt."},{"year":"2021-2013:","title":"Cloud-native Anwendungsarchitekturen","description":"Best Practices für das Design cloud-nativer Anwendungen untersucht."},{"year":"2019-2020:","title":"KI-gestützte Personalisierung der Nutzererfahrung","description":"KI genutzt, um Nutzererlebnisse basierend auf Verhalten zu personalisieren."}]},"experience2":{"heading":"Ausbildung","loading_label":"Wird geladen...","loading_text":"Bitte warten","error_label":"Fehlgeschlagen","error_text":"Ausbildungsdaten konnten nicht geladen werden.","empty_label":"Keine Einträge","empty_text":"Keine Ausbildungseinträge gefunden.","research_heading":"Recherchiert","research_items":[{"year":"2023-2024:","title":"Erweiterte Datenanalyse mit Big-Data-Tools","description":"Big-Data-Tools für fortgeschrittene Analysen und Einblicke eingesetzt."},{"year":"2021-2013:","title":"Cloud-native Anwendungsarchitekturen","description":"Best Practices für das Design cloud-nativer Anwendungen untersucht."},{"year":"2019-2020:","title":"KI-gestützte Personalisierung der Nutzererfahrung","description":"KI genutzt, um Nutzererlebnisse basierend auf Verhalten zu personalisieren."}]}}')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `updated_at` = CURRENT_TIMESTAMP(3);
