name: Sync to Server

on:
  push:
    branches:
      - main # Ana branch'inizi yazın

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo'yu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Dosyaları Sunucuya Senkronize Et
      - name: Sync files to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 141.136.36.40
          username: guzelwebdesign
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/guezelwebdesign
            git reset --hard # Çakışmaları önlemek için hard reset
            git pull origin main
            npm ci # Bağımlılıkları yüklemek için
            npm run build # Projeyi yeniden build etmek için

